#!/bin/bash

echo '<?xml version="1.0" encoding="UTF-8"?>'
echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'

for PAGE in $@; do
    TS=$(date -u -Iseconds -d "$(stat -c %y build/$PAGE)")
    echo '  <url>'
    echo '    <loc>https://buildbotics.com/'$PAGE'</loc>'
    echo '    <lastmod>'$TS'</lastmod>'
    echo '  </url>'
done

echo '</urlset>'
